### ISSUE TITLE
Cosmetic Bug: "Error" messages from files with "error" in name

### ISSUE THREAD

**Issue by ThioJoe** [aws-solutions/amazon-s3-glacier-refreezer#10]
**Describe the bug**
In the CloudWatch management console, while the stack is running, an error message is logged when there is no actual apparent error, but rather it's just an info message for any file / directory being copied that has the string "error" within it.

**To Reproduce**
For the transfer, use a .csv mapping file as described in the implementation guide, where some entries contain the string 'error' within the "FileName" column.

**Expected behavior**
Only actual errors would be displayed in the error message box.

**Please complete the following information about the solution:**
- [x] Version: 1.0.1

- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository?  -- No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? -- N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?  -- Not relevant I believe
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
I blacked out some info where I wasn't sure what it was for just out of an abundance of caution. These are all the error messages that appeared during the processing. Screenshot was taken after everything was done.
![Error Messages](https://user-images.githubusercontent.com/12518330/123667287-dcb57580-d7ee-11eb-9f29-383e3014fe58.png)

**Additional context**
The files both appear to have copied without issue. The only two files in the 'error' messages are also the only two files in the vault that contain the string 'error' (I searched the csv mapping file to be sure).

The files were originally uploaded to the old glacier using FastGlacier software. Looking at the inventory file retrieved from old glacier, FastGlacier encodes the file paths/names in base64 inside the "ArchiveDescription" field. Therefore, the string 'error' does not occur anywhere in the raw inventory file on AWS's side (I searched to be sure), only in the csv mapping file. So I'm not sure if this would also happen if the string occurred in the actual inventory file.

Appears to only be cosmetic but did confuse me when I saw the messages pop up.

**Comment by eminaws** [comment]
Thank you, @ThioJoe - appreciate the detailed write up. 

Indeed - the insights widget in the dashboard looks for word Error/error in the description. Let me check how we can differentiate it better.

**Comment by bassemwanis** [comment]
In December 2023, the [Data Transfer from Amazon S3 Glacier Vaults to Amazon S3](https://aws.amazon.com/solutions/implementations/data-transfer-from-amazon-s3-glacier-vaults-to-amazon-s3/) solution replaced this solution.

This issue should no longer persist in the new solution. However, if you encounter a similar issue, please create a new issue against the new GitHub [repository](https://github.com/aws-solutions/data-transfer-from-amazon-s3-glacier-vaults-to-amazon-s3).
