### ISSUE TITLE
Files from Glacier with Non-English characters not transferring correctly

### ISSUE THREAD

**Issue by Warpkitty** [aws-solutions/amazon-s3-glacier-refreezer#11]
**Describe the bug**
I've run the script (1.01) and transferred data to an S3 bucket. During the transfer I noticed errors in Cloudwatch (which I didn't save). On inspecting the S3 bucket, file names with German umlauts were being renamed (ü to C<) and ones with Greek letters also (μ to B5).

**To Reproduce**
Transfer non English file name to S3 bucket using refreezer script v 1.01

**Expected behavior**
Non-English characters should transfer and not be displayed as the Unicode character

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_Amazon S3 Glacier Re:Freezer. Version **v1.0.0**_".

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas]
- [ ] Yes
- [ ] (https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?
- [ ] Yes, but I neglected to record them.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by Warpkitty** [comment]
I found the error messages (repeated 900+ times)

2021-07-21T04:01:32.904Z 35fa2123-3c7b-5f32-8d0e-7852a229ebec ERROR Invoke Error {"errorType":"BadRequest","errorMessage":null,"code":"BadR

**Comment by eminaws** [comment]
Thank you for bringing this in @Warpkitty - we will have a look.

**Comment by jamesliusongyu** [comment]
Hi @Warpkitty , thanks for raising this issue. In order for us to have a fuller understanding of the issue, we would like to have more information. How were the files with non-English archive description uploaded into the Glacier Vault? Was it via AWS CLI / SDK, or via third party software?

**Comment by Warpkitty** [comment]
I used FastGlacier to upload the files.

**Comment by bassemwanis** [comment]
In December 2023, the [Data Transfer from Amazon S3 Glacier Vaults to Amazon S3](https://aws.amazon.com/solutions/implementations/data-transfer-from-amazon-s3-glacier-vaults-to-amazon-s3/) solution replaced this solution.

This issue should no longer persist in the new solution. However, if you encounter a similar issue, please create a new issue against the new GitHub [repository](https://github.com/aws-solutions/data-transfer-from-amazon-s3-glacier-vaults-to-amazon-s3).
